% interactcadsample.tex
% v1.04 - May 2023

\documentclass[]{interact}

\usepackage{epstopdf}% To incorporate .eps illustrations using PDFLaTeX, etc.
\usepackage{subfigure}% Support for small, `sub' figures and tables
%\usepackage[nolists,tablesfirst]{endfloat}% To `separate' figures and tables from text if required

\usepackage{natbib}% Citation support using natbib.sty
\bibpunct[, ]{(}{)}{;}{a}{}{,}% Citation support using natbib.sty
\renewcommand\bibfont{\fontsize{10}{12}\selectfont}% Bibliography support using natbib.sty

\theoremstyle{plain}% Theorem-like structures provided by amsthm.sty
\newtheorem{theorem}{Theorem}[section]
\newtheorem{lemma}[theorem]{Lemma}
\newtheorem{corollary}[theorem]{Corollary}
\newtheorem{proposition}[theorem]{Proposition}

\theoremstyle{definition}
\newtheorem{definition}[theorem]{Definition}
\newtheorem{example}[theorem]{Example}

\theoremstyle{remark}
\newtheorem{remark}{Remark}
\newtheorem{notation}{Notation}


% tightlist command for lists without linebreak
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



\usepackage{lscape}
\usepackage{hyperref}
\usepackage[utf8]{inputenc}
\def\tightlist{}
\usepackage{setspace}
\doublespacing

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}

\begin{document}


\articletype{}

\title{Automated Assessment of Residual Plots with Computer Vision
Models}


\author{\name{Weihao Li$^{a, b}$, Dianne Cook$^{a}$, Emi
Tanaka$^{b}$, Susan VanderPlas$^{c, d}$, Klaus Ackermann$^{a}$}
\affil{$^{a}$Department of Econometrics and Business Statistics, Monash
University, Clayton, VIC, Australia; $^{b}$Research School of Finance,
Actuarial Studies and Statistics, Australian National University, Acton,
ACT, Australia; $^{c}$Department of Statistics, University of Nebraska,
Lincoln, Nebraska, USA; $^{d}$Department of Mathematics \& Statistics,
Utah State University, Logan, Utah}
}


\maketitle

\begin{abstract}
Plotting the residuals is a recommended procedure to diagnose deviations
from linear model assumptions, such as non-linearity,
heteroskedasticity, and non-normality. The presence of structure in
residual plots can be tested using the lineup protocol to do visual
inference. There are a variety of conventional residual tests, but the
lineup protocol, used as a statistical test, performs better for
diagnostic purposes because it is less sensitive and applies more
broadly to different types of departures. However, the lineup protocol
relies on human judgment which limits its scalability. This work
presents a solution by providing a computer vision model to automate the
assessment of residual plots. It is trained to predict a distance
measure that quantifies the disparity between the residual distribution
of a fitted classical normal linear regression model and the reference
distribution, based on Kullback-Leibler divergence. Evaluation using
data from a prior human-subject experiment shows the model exhibits
lower sensitivity than conventional tests but higher sensitivity than
human visual tests. Several examples from classical papers and
contemporary data demonstrate the method's practical utility in
automating residual diagnostics.
\end{abstract}

\begin{keywords}
statistical graphics; data visualization; visual inference; computer
vision; machine learning; hypothesis testing; regression analysis;
cognitive perception; simulation; practical significance
\end{keywords}

\section{Introduction}\label{sec-model-introduction}

Plotting residuals is commonly regarded as a standard practice in linear
regression diagnostics \citep{belsley1980regression, cook1982residuals}.
This visual assessment plays a crucial role in identifying whether key
model assumptions, such as linearity, homoscedasticity, and normality,
are reasonable. It also helps in understanding the goodness of fit and
various unexpected characteristics of the model.

Generating a residual plot in most statistical software is often as
straightforward as executing a line of code or clicking a button.
However, accurately interpreting a residual plot can be challenging, as
some features are a result of predictor characteristics and natural
variation, while others indicate violations of model assumptions
\citep{li2024plot}. For example, in Figure \ref{fig:false-finding}, the
residual plot displays a triangular left-pointing shape. The distinct
difference in the spread of the residuals across the fitted values might
lead analysts to suspect heteroskedasticity. In this case, however, the
fitted regression model is correctly specified, and the triangular shape
is actually a result of the skewed distribution of the predictors,
rather than indicating a flaw in the model.

\begin{figure}[!h]

{\centering \includegraphics[width=0.5\linewidth]{paper_files/figure-latex/false-finding-1} 

}

\caption{An example residual vs fitted values plot (red line indicates 0 corresponds to the x-intercept, i.e. $y=0$). The vertical spread of the data points varies with the fitted values. This often indicates the existence of heteroskedasticity, however, here the result is due to skewed distribution of the predictors rather than heteroskedasticity. The Breusch-Pagan test rejects this residual plot at 5\% significance level ($p\text{-value} = 0.046$).}\label{fig:false-finding}
\end{figure}

The concept of visual inference, as proposed by
\citet{buja2009statistical}, provides an inferential framework for
assessing whether residual plots contain visual patterns inconsistent
with the model assumptions. In this framework, a \textbf{true residual
plot} refers to the residual plot obtained from the observed data under
the fitted regression model. In contrast, \textbf{null plots} are
synthetic residual plots generated under the null hypothesis \(H_0\),
where the linear regression model is correctly specified. These null
plots are constructed by generating residuals from the residual rotation
distribution \citep{langsrud2005rotation}, which preserves the structure
implied by \(H_0\) (see Section \ref{sec-model-statistical-testing} for
details).

The goal is to assess whether the true residual plot is visually
distinguishable from the null plots. This is typically done using the
lineup protocol (Figure \ref{fig:ex-lineup}), where the true residual
plot is embedded among multiple null plots. Successful identification of
the true residual plot provides evidence against \(H_0\).

\begin{figure}[!h]

{\centering \includegraphics[width=1\linewidth]{paper_files/figure-latex/ex-lineup-1} 

}

\caption{An example lineup embedding the true residual plot among four null plots. In practice, lineups typically include 19 null plots, but a reduced set is shown here for presentation purposes. The null plots are generated via residual rotation to ensure consistency with $H_0$. Observers who have not previously seen the lineup are asked to identify the plot that appears most different. Under $H_0$ that the regression model is correctly specified, the true residual plot should be indistinguishable from the null plots, yielding a selection probability of 0.2. A small $p$-value arises when a substantial proportion of observers select the true residual plot (shown at position 2, exhibiting non-linearity).}\label{fig:ex-lineup}
\end{figure}

The practice of delivering a residual plot as a lineup is generally
regarded as a valuable approach. Beyond its application in residual
diagnostics, the lineup protocol has been integrated into the analysis
of diverse subjects. For instance, Loy and Hofmann
\citetext{\citeyear{loy2013diagnostic}; \citeyear{loy2014hlmdiag}; \citeyear{loy2015you}}
illustrated its applicability in diagnosing hierarchical linear models.
Additionally, \citet{widen2016graphical} and \citet{fieberg2024using}
demonstrated its utility in geographical and ecology research
respectively, while \citet{krishnan2021hierarchical} explored its
effectiveness in forensic examinations.

A practical limitation of the lineup protocol lies in its reliance on
human judgments \citep[see][]{li2024plot}. Unlike conventional
statistical tests that can be performed using a statistical software,
the lineup protocol requires human evaluation of images. This
characteristic makes it less suitable for large-scale applications,
given the associated high labor costs and time requirements. There is a
substantial need to develop an approach to substitute these human
judgement, for example through the automated interpretation of data
plots using computer vision.

Efforts to automate plot interpretation date back to early work like
Tukey's ``Scagnostics'' \citep{tukey1985computer}, which is a set of
numerical statistics that summarize features of scatter plots.
\citet{wilkinson2005graph} expanded on this work, introducing
scagnostics based on computable measures applied to planar proximity
graphs. These measures, including, but not limited to, ``Outlying'',
``Skinny'', ``Stringy'', ``Straight'', ``Monotonic'', ``Skewed'',
``Clumpy'', and ``Striated'', aimed to characterize outliers, shape,
density, trend, coherence and other characteristics of the data.
However, such measures may not capture the full range of visual patterns
necessary for residual diagnostics \citep{buja2009statistical}. A more
promising direction lies in enabling computers to learn the relevant
visual features directly mirroring how humans intuitively interpret
plots.

Modern computer vision models rely on deep neural networks with
convolutional layers \citep{fukushima1982neocognitron}. These layers use
small, sliding windows to scan the image, performing a dot product to
extract local features and patterns. Numerous studies have demonstrated
the efficacy of convolutional layers in addressing various vision tasks,
including image recognition \citep{rawat2017deep}. Despite the
widespread use of computer vision models in fields like computer-aided
diagnosis \citep{lee2015image}, pedestrian detection
\citep{brunetti2018computer}, and facial recognition
\citep{emami2012facial}, their application in reading data plots remains
limited. While some studies have explored the use of computer vision
models for tasks such as reading recurrence plots for time series
regression \citep{ojeda2020multivariate}, time series classification
\citep{chu2019automatic, hailesilassie2019financial, hatami2018classification, zhang2020encoding},
anomaly detection \citep{chen2020convolutional}, and pairwise causality
analysis \citep{singh2017deep}, the application of reading residual
plots with computer vision models is a new field of study.

In this paper, we develop computer vision models and integrate them into
the residual plot diagnostics workflow, addressing the need for
automated visual inference. The model is a regression-based computer
vision system that takes a residual plot as input and outputs a
non-negative estimated distance \(\hat{D}\). Training and test data are
generated from a synthetic data model, simulating residual plots under
various violation scenarios, with targets defined as customized
distances \(D\) computed from the underlying data generating process,
quantifying the extent of model violations. The model is evaluated on
held-out test plots for its ability to estimate \(\hat{D}\). In
addition, we develop a statistical testing procedure based on
\(\hat{D}\) for detecting model misspecification, and compare its
performance with classical residual diagnostic tests as well as results
from a human-subject visual inference experiment using the lineup
protocol.

The paper is structured as follows. Section
\ref{sec-model-specifications} discusses different specifications of the
computer vision models. Section
\ref{sec-model-distance-between-residual-plots} introduces the distance
measure used to quantify model violations, while Section
\ref{sec-model-distance-estimation} describes how this measure is
estimated using computer vision models, including the model
architecture, data generation, and training procedure. Section
\ref{sec-model-statistical-testing} describes statistical tests based on
the estimated distance, and Section \ref{sec-bootstrap-assessment}
presents bootstrap-based methods for assessing the variability of
estimated distance and the stability of model misspecification
conclusions. Results are reported in Section \ref{sec-model-results},
followed by illustrative applications on example datasets in Section
\ref{sec-examples}. Finally, we conclude with a discussion of the
findings and outline directions for future research.

\section{Model Specifications}\label{sec-model-specifications}

There are various specifications of the computer vision model that can
be used to assess residual plots. We discuss these specifications below
focusing on the input and the output formats.

\subsection{Input Formats}\label{input-formats}

Deep learning models are sensitive to input design, and several
alternatives are available for encoding residual plots. A simple
approach involves feeding vectors of residuals and fitted values into
the model. While this format contains all relevant information, the
input length varies with sample size, which conflicts with the
fixed-shape requirements of modern vision models such as those
implemented in TensorFlow \citep{abadi2016tensorflow}. Padding can be
used to enforce uniform length but risks truncation if inputs exceed the
fixed size. Alternatively, fixed-size sampling of residual--fitted value
pairs can ensure consistency, though at the cost of some information
loss.

Another strategy is to convert residual plots into images. This enables
the use of standard convolutional architectures in computer vision such
as VGG16 \citep{simonyan2014very}. Image-based inputs offer a richer
representation by preserving the joint distribution of residuals and
fitted values in a visually interpretable format, helping models more
effectively capture spatial structure and local correlations than
vector-based formats. To ensure model generalization, it is essential to
use residual plots in a consistent style, i.e., same aesthetics, layout,
scaling and color schemes.

Using multiple residual plots as input, such as pairs, triplets, or full
lineups is also a possible option. For instance, triplet networks
\citep{chopra2005learning} can assess visual similarity if we assume
null plots are more similar to each other than to the true residual
plot, which may help distinguish null plots from true residual plots.
However, these architectures introduce complexity in training due to
weight sharing and specialized loss functions. We experimented with this
setting in a pilot study, and found multiple residual plots led to high
input resolution, high computational cost and suboptimal model
performance. Balancing accuracy, interpretability, and implementation
cost, we adopt a single residual plot in image format as the model
input.

\subsection{Output Formats}\label{output-formats}

Given the input is a single fixed-resolution image, the model output can
be defined for various tasks, including binary classification,
multiclass classification, and numeric regression.

In the binary case, the outcome may indicate whether the input image is
consistent with a null plot, as determined either by (1) the
data-generating process or (2) the outcome of a visual test based on
human judgment. The first approach models the probability that a
residual plot is not a null plot and is a viable option. In contrast,
the second relies on experimental data that are often scarce or
inconsistent across studies.

Alternatively, a multiclass outcome may classify images into categories
such as ``contains outliers'' vs.~``does not contain outliers'' or ``is
non-linear'' vs.~``not non-linear,'' among other diagnostic features.
While this approach is appealing in theory, it essentially reverts to
the traditional testing framework, where tests focus on detecting
specific types of model violations in isolation.

A third option is to produce a meaningful and interpretable numerical
measure that quantifies the strength of suspicious visual patterns
reflecting the extent of model violations, or the difficulty index for
identifying whether a residual plot has no issues. However, such
measures are often used informally in daily communications but are
rarely formalized. For supervised learning, they must be clearly defined
and reliably estimable.

In this study, we formulate the output as a continuous measure of
deviation from model assumptions. Compared to probability outputs based
on binary labels (true residual plots labeled as 1 and null plots as 0),
this formulation explicitly encodes the severity of violations and
avoids forcing the model to infer such structure solely from the data
distribution, which can be inefficient and discards useful prior
knowledge.

\section{Distance from a Theoretically ``Good'' Residual
Plot}\label{sec-model-distance-between-residual-plots}

A numerical measure of ``difference'' or ``distance'' between plots can
take the form of a basic statistical operation on pixels, such as the
sum of squared differences. However, direct pixel-to-pixel comparisons
are not well suited to residual plots, where the primary interest lies
in structural patterns. Alternatively, the distance can be based on
established image similarity metrics such as the Structural Similarity
Index Measure \citep{wang2004image}, which compares images using
contrast, luminance, and structure (related to the average, standard
deviation, and correlation of pixel values within a window,
respectively). These metrics are designed for general image comparison
tasks that differ substantially from evaluating data plots, where only
essential plot elements are relevant \citep{chowdhury2018measuring}.
Another direction is to define distance using key scatter plot
characteristics, such as those captured by scagnostics (see Section
\ref{sec-model-introduction}), although the functional form must be
carefully designed to reflect model violations meaningfully.

In this section, we introduce a distance measure between a true residual
plot and a theoretically ``good'' residual plot. This measure quantifies
the divergence between the residual distribution of a given fitted
regression model and that of a correctly specified model. Its
construction assumes knowledge of the data generating processes for both
predictors and response variables. Since these processes are often
unknown in practice, Section \ref{sec-model-distance-estimation}
discusses how the distance can be estimated using a computer vision
model, while Section \ref{sec-model-statistical-testing} describes a
statistical test based on the estimated distance.

\subsection{Residual Distribution}\label{residual-distribution}

Consider the classical normal linear regression model,
\(\boldsymbol{y}=\boldsymbol{X}\boldsymbol{\beta}+\boldsymbol{e}\),
where \(\boldsymbol{y}\) is the \(n\times 1\) response vector,
\(\boldsymbol{X}\) is the design matrix, \(\boldsymbol{\beta}\) is a
vector of regression coefficients and \(\boldsymbol{e}\) is the vector
of random errors. The residual vector is
\(\hat{\boldsymbol{e}}=\boldsymbol{y}-\hat{\boldsymbol{y}} = \boldsymbol{R}\boldsymbol{e}\),
where
\(\boldsymbol{R}=\boldsymbol{I}_n-\boldsymbol{X}(\boldsymbol{X}^\top\boldsymbol{X})^{-1}\boldsymbol{X}^\top\)
is the residual operator, and \(\boldsymbol{I}_n\) is the \(n\times n\)
identity matrix.

Under the classical assumptions
\(\boldsymbol{e}\sim \mathcal{N}(\boldsymbol{0}_n,\sigma^2\boldsymbol{I}_n)\),
the residuals are also Gaussian, since they are a linear transformation
of \(\boldsymbol{e}\). We refer to this induced distribution as the
reference distribution \(Q\), which characterizes the residual behaviour
under correct model specification and depends only on
\(\boldsymbol{X}\).

If \(\boldsymbol{X}\) has full column rank \(k\), then
\(\text{rank}(\boldsymbol{R}) = n - k\), and
\(\mathrm{cov}(\hat{\boldsymbol{e}})=\sigma^2\boldsymbol{R}\) is
singular. Hence, \(Q\) is a degenerate Gaussian supported on an
\((n-k)\)-dimensional subspace. To obtain a non-degenerate reference
distribution required for the distance computation in Section
\ref{sec-distance-of-p-from-q}, we replace \(\sigma^2\boldsymbol{R}\)
with its diagonal approximation,
\(\mathrm{diag}(\sigma^2\boldsymbol{R})\), yielding
\(Q \approx \mathcal{N}\left(\boldsymbol{0}_n,\mathrm{diag}(\sigma^2\boldsymbol{R})\right)\).

The reference distribution \(Q\) corresponds to the correct model
specification. Under misspecification, the residuals follow a different
distribution \(P\). For example, omitted variables correlated with
\(\boldsymbol{X}\) alter the residual structure, causing \(P\) to
deviate from \(Q\). Similarly, non-Gaussian error distributions
(e.g.~multivariate lognormal) induce skewness and heavier tails.

\subsection{\texorpdfstring{Distance of \(P\) from
\(Q\)}{Distance of P from Q}}\label{sec-distance-of-p-from-q}

We define the distance of the true residual distribution \(P\) from the
reference residual distribution \(Q\) based on the Kullback--Leibler
divergence \citep{kullback1951information}:
\begin{equation} \label{eq:kl-0}
D = \log\left(1 + D_{KL}(P \| Q)\right),
\end{equation} \noindent where \(D_{KL}(P \| Q)\) is defined as
\begin{equation} \label{eq:kl-1}
D_{KL}(P \| Q) = \int_{\mathbb{R}^{n}}\log\frac{p(\hat{\boldsymbol{e}})}{q(\hat{\boldsymbol{e}})}p(\hat{\boldsymbol{e}})d\hat{\boldsymbol{e}},
\end{equation} \noindent and \(p(\cdot)\) and \(q(\cdot)\) are the
probability density functions for \(P\) and \(Q\), respectively.

This measure was introduced in \citet{li2024plot} to quantify the effect
size of non-linearity and heteroskedasticity in residual plots. In the
presence of model misspecification, if the error structure deviates from
\(\boldsymbol{e} \sim \mathcal{N}(\boldsymbol{0}_n,\sigma^2\boldsymbol{I}_n)\),
for instance with covariance \(\boldsymbol{V}\) and omitted higher-order
terms \(\boldsymbol{Z}\boldsymbol{\beta}_z\) correlated with
\(\boldsymbol{X}\), the induced residual distribution can be expressed
as
\(P = \mathcal{N}(\boldsymbol{R}\boldsymbol{Z}\boldsymbol{\beta}_z, \text{diag}(\boldsymbol{R}\boldsymbol{V}\boldsymbol{R}))\),
where the diagonal approximation ensures non-degenerate covariance
matrix. The transformation \(D = \log(1 + D_{KL})\) compresses large
values of \(D_{KL}\), improves numerical stability during estimation
(Section \ref{sec-model-distance-estimation}), and ensures that \(D\) is
well-defined when \(D_{KL} = 0\).

Since \(P\) and \(Q\) are taken as non-degenerate Gaussian
distributions, the KL divergence admits the closed form
\begin{equation} \label{eq:kl-2}
D_{KL}(P \| Q) = \frac{1}{2}\left(\log\frac{|\boldsymbol{W}|}{|\text{diag}(\boldsymbol{R}\sigma^2)|} - n + \text{tr}(\boldsymbol{W}^{-1}\text{diag}(\boldsymbol{R}\sigma^2)) + \boldsymbol{\mu}_z^\top\boldsymbol{W}^{-1}\boldsymbol{\mu}_z\right),
\end{equation} \noindent where
\(\boldsymbol{\mu}_z = \boldsymbol{R}\boldsymbol{Z}\boldsymbol{\beta}_z\),
and
\(\boldsymbol{W} = \text{diag}(\boldsymbol{R}\boldsymbol{V}\boldsymbol{R})\).
The assumed error variance \(\sigma^2\) is set to be
\(\text{tr}(\boldsymbol{V})/n\), which is the expectation of the
estimated variance.

\subsection{\texorpdfstring{Non-normal
\(P\)}{Non-normal P}}\label{non-normal-p}

When the error vector \(\boldsymbol{e}\) is non-Gaussian, the induced
residual distribution \(P\) is generally non-Gaussian and typically
unavailable in closed form. Consequently, the Gaussian closed-form
expression in Equation \ref{eq:kl-2} is no longer applicable, and the KL
divergence must instead be evaluated from its definition in Equation
\ref{eq:kl-1}. This requires high-dimensional integration over the
residual space, rendering direct evaluation impractical for large \(n\).

To obtain a tractable approximation, we assume that the residual
components \(\{\hat{e}_i\}_{i=1}^n\) are mutually independent, so that
\(p(\hat{\boldsymbol{e}}) \approx \prod_{i=1}^n p_i(\hat{e}_i)\) and
\(q(\hat{\boldsymbol{e}}) \approx \prod_{i=1}^n q_i(\hat{e}_i)\). This
assumption holds for
\(Q \approx \mathcal{N}\left(\boldsymbol{0}_n,\mathrm{diag}(\sigma^2\boldsymbol{R})\right)\),
which has independent components, but generally does not hold for \(P\).
Nevertheless, it removes the need for high-dimensional integration and
reduces the computation to univariate densities, substantially lowering
computational cost.

Under this factorisation, the KL divergence decomposes additively:
\[D_{KL}(P \| Q) \approx \sum_{i=1}^n \int_{\mathbb{R}} p_i(\hat{e}_i)\log\frac{p_i(\hat{e}_i)}{q_i(\hat{e}_i)} d\hat{e}_i = \sum_{i=1}^n \mathbb{E}_{p_i}\left[\log\frac{p_i(\hat{e}_i)}{q_i(\hat{e}_i)}\right],\]
\noindent where \(p_i\) and \(q_i\) denote the marginal densities of
\(\hat{e}_i\) under \(P\) and \(Q\), respectively.

We approximate the expectation via Monte Carlo simulation. Specifically,
we generate independent samples \(\{\boldsymbol{e}^{(j)}\}_{j=1}^m\)
from the error distribution and obtain residual vectors
\(\boldsymbol{B}_j = \boldsymbol{R}\boldsymbol{e}^{(j)}\). The marginal
density \(p_i\) is then estimated from \(\{B_{ij}\}_{j=1}^m\) using a
Gaussian kernel density estimator with bandwidth selected by Silverman's
rule of thumb \citep{silverman2018density}, where \(B_{ij}\) denotes the
\(i\)-th component of \(\boldsymbol{B}_j\). This yields
\[D_{KL}(P \| Q) \approx \sum_{i=1}^n \mathbb{E}_{p_i}\left[\log\frac{p_i(\hat{e}_i)}{q_i(\hat{e}_i)}\right] \approx \sum_{i=1}^n\frac{1}{m}\sum_{j=1}^m \log\frac{\hat{p}_i(B_{ij})}{q_i(B_{ij})},\]
\noindent where \(q_i(\cdot)\) denotes the Gaussian reference density
with variance \(\hat{\sigma}^2R_{ii}\), with
\(\hat{\sigma}^2 = \frac{1}{nm - 1}\sum_{b \in \mathrm{vec}(\boldsymbol{B})} \left(b - \bar{b}\right)^2\)
and
\(\bar{b} = \frac{1}{nm}\sum_{b \in \mathrm{vec}(\boldsymbol{B})} b\).

\section{Distance Estimation Using Computer Vision
Models}\label{sec-model-distance-estimation}

The distance measure defined in Equation \ref{eq:kl-0} quantifies the
difference between the true residual distribution \(P\) and the
reference distribution \(Q\). However, it can only be computed when the
data-generating process is known, which is rarely the case in practice.

To estimate this distance from a residual plot, we define a computer
vision estimator \begin{equation*} \label{eq:d-approx}
\hat{D} = f_{CV}(V_{h \times w}(\boldsymbol{e}, \hat{\boldsymbol{y}}), \boldsymbol{s}),
\end{equation*} \noindent where \(V_{h \times w}(\cdot)\) denotes the
rendering function that coverts a residuals vs.~fitted values plot into
an \(h \times w\) RGB image, with h and w denoting the image height and
width (in pixels), respectively. Here, \(\boldsymbol{s}\) is a vector of
auxiliary features including scagnostics measures and sample size, and
\(f_{CV}(\cdot)\) maps the image and auxiliary features to an estimated
distance \(\hat{D} \in [0, +\infty)\). Details of the model architecture
and training procedure are provided in Sections
\ref{sec-model-architecture} and \ref{sec-model-data-generation},
respectively.

The auxiliary feature vector \(\boldsymbol{s}\) is included to
complement information encoded in the residual plot image. While
\(V_{h \times w}(\cdot)\) captures visual patterns of misspecification,
certain attributes such as sample size are not recoverable from the
image. In addition, we include scagnostics as useful graph-based
summaries of scatter plot structure, which have been shown to be
effective descriptors of shape, clustering, and outliers in exploratory
data analysis.

The distance estimator \(\hat{D}\) quantifies how closely the residuals
resemble the reference distribution \(Q\) and, after adjusting for
sample size effects, can be used as an index of model violation severity
(see Appendix D for details). However, since a single residual plot may
not fully characterize the underlying residual distribution, \(\hat{D}\)
is not expected to equal the true distance \(D\). Residual plots
generated from the same distribution \(P\) may also vary visually,
particularly for small \(n\), introducing estimation error that depends
on the representativeness of the input plot.

\subsection{Model Architecture}\label{sec-model-architecture}

The architecture of the computer vision model \(f_{CV}\) is adapted from
the well-established VGG16 architecture \citep{simonyan2014very}. While
more recent architectures like ResNet \citep{he2016deep} and
DenseNet\citep{huang2017densely}, have achieved even greater
performance, VGG16 remains a solid choice for many applications due to
its simplicity and effectiveness. Our decision to use VGG16 aligns with
our goal of starting with a proven and straightforward model. Figure
\ref{fig:cnn-diag} illustrates the architecture, while Appendix B
provides detailed layer specifications.

\begin{figure}[!h]

{\centering \includegraphics[width=1\linewidth]{figures/cnn} 

}

\caption{Diagram of the architecture of the optimized computer vision model. Numbers at the bottom of each box show the shape of the output of each layer. The band of each box drawn in a darker color indicates the use of the rectified linear unit activation function.  Yellow boxes are 2D convolutional layers, orange boxes are pooling layers, the grey box is the concatenation layer, and the purple boxes are dense layers.}\label{fig:cnn-diag}
\end{figure}

The model accepts residual plots rendered as \(h \times w\) RGB images,
with \(h,w \in \{32, 64, 128\}\), allowing us to study the effect of
image resolution on predictive performance while balancing computational
cost. Images are first converted to grayscale using the Rec. 601 luma
formula \citep{series2011studio}, as the data points are plotted in
black on a white background. The background also includes a red
reference line at \(y = 0\), which is preserved under this conversion.

The processed images are used as input to the first convolutional block.
The model consists of up to five consecutive convolutional blocks,
mirroring the original VGG16 architecture. Within each block, two
\(3 \times 3\) convolutional layers are applied, each followed by batch
normalization for training stability and a rectified linear unit (ReLU)
activation for non-linearity. The block concludes with a \(2 \times 2\)
max-pooling layer that downsamples the spatial dimensions by taking the
maximum over non-overlapping windows for each channel. A dropout layer
is then applied at the end of each block to randomly deactivate
activations during training, improving regularization.

The final convolutional output is aggregated using either global
max-pooling or global average-pooling, producing a two-dimensional
feature representation. This feature representation is concatenated with
an \(n \times 5\) tensor containing the ``Monotonic'', ``Sparse'',
``Splines'', and ``Striped'' measures computed using the
\texttt{cassowaryr} R package \citep{mason2022cassowaryr}, along with
the sample size for each residual plot. \footnote{Note: These measures
  were selected for their reliability and computational efficiency.
  Other scagnostics were excluded because they occasionally caused R
  process crashes (\(\sim 5\%\)) during data preparation due to a bug in
  the \texttt{interp} package \citep{Albrecht2023interp}. Although this
  issue was later fixed at our request, the corrected version was not
  available during model training, and the full set of features was also
  deemed too computationally expensive for efficient inference.}

The concatenated feature tensor is passed to the final prediction block,
which consists of two fully connected layers. The first layer has at
least \(128\) units and is followed by batch normalization and dropout
for regularization. The second fully connected layer contains a single
unit, followed by a ReLU activation to enforce non-negative outputs,
producing the final scalar prediction.

\subsection{Data Generation and Model
Training}\label{sec-model-data-generation}

To train the computer vision model for estimating \(\hat{D}\), we
constructed a dataset of paired residual plots and their corresponding
\(D\) values. In deep learning, synthetic data are commonly used for
training vision models when labelled data are scarce, costly, or
difficult to obtain reliably \citep{nikolenko2021synthetic}. This is
particularly appropriate when the data-generating mechanism is well
specified, enabling controlled generation of large-scale examples that
encode known structural violations. Accordingly, we generated 80,000
training samples and 8,000 test samples, providing full control over the
generative process, exact computation of \(D\), and broad coverage of
residual patterns associated with model misspecification.

The simulated data incorporated three common types of residual
departures: non-linearity, heteroskedasticity, and non-normality. These
effects were induced by fitting a simple linear regression model to data
generated from a more flexible underlying process based on Hermite
polynomials \citep{hermite1864nouveau}, multiple predictors, and a range
of predictor and error distributions. A comprehensive grid of parameter
settings was used to produce diverse residual behaviours, including
configurations with multiple simultaneous violations.

To ensure uniform coverage across the target space of \(D\), we adopted
a bucketed sampling strategy. Specifically, simulated samples were
iteratively generated and assigned to one of 50 bins corresponding to
quantiles of \(D\), with acceptance controlled to balance representation
across difficulty levels. Table \ref{tab:data-overall} summarises the
resulting sample sizes for each violation scenario.

\begin{table}
\centering
\caption{\label{tab:data-overall}Number of training and test samples for each model violation scenario, including cases with multiple simultaneous violations. Each sample consists of a residual plot as input and the corresponding distance $D$ as the target. Root mean square error (RMSE) values for the training and test sets are shown for each scenario. Details of the synthetic data generating process used to construct these samples are provided in Appendix A.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{lrrlr}
\toprule
\multicolumn{1}{c}{ } & \multicolumn{2}{c}{Train} & \multicolumn{2}{c}{Test} \\
\cmidrule(l{3pt}r{3pt}){2-3} \cmidrule(l{3pt}r{3pt}){4-5}
Violations & \#samples & RMSE & \#samples & RMSE\\
\midrule
no violations & 1,546 & 1.149 & 155 & 1.267\\
non-linearity & 22,184 & 0.625 & 2,218 & 0.787\\
heteroskedasticity & 10,826 & 0.528 & 1,067 & 0.602\\
non-linearity + heteroskedasticity & 10,221 & 0.593 & 985 & 0.751\\
non-normality & 10,797 & 0.279 & 1,111 & 0.320\\
non-linearity + non-normality & 8,835 & 0.472 & 928 & 0.600\\
heteroskedasticity + non-normality & 7,870 & 0.354 & 819 & 0.489\\
non-linearity + heteroskedasticity + non-normality & 7,721 & 0.432 & 717 & 0.620\\
\bottomrule
\end{tabular}}
\end{table}

Computer vision model parameters \(\boldsymbol{\theta}\) were randomly
initialized using the Glorot Uniform method
\citep{glorot2010understanding} and optimized with the Adam optimizer
\citep{kingma2014adam} under a mean squared error objective:
\[\hat{\boldsymbol{\theta}} = \underset{\boldsymbol{\theta}}{\text{arg min}}\frac{1}{n_{\text{train}}}\sum_{i=1}^{n_{\text{train}}}(D_i - f_{\boldsymbol{\theta}}(V_i, \boldsymbol{s}_i))^2,\]
\noindent where \(n_{\text{train}}\) denotes the number of training
samples, \(V_i\) is the \(i\)-th residual plot, and \(\boldsymbol{s}_i\)
represents the auxiliary tabular features, including four scagnostics
measures and sample size.

The model was trained on paired inputs consisting of RGB residual plot
images and corresponding \(D\) values, with the objective of learning
the mapping \(\hat{D} = f_{\boldsymbol{\theta}}(V, \boldsymbol{s})\).
Training was conducted on the MASSIVE M3 high-performance computing
platform \citep{goscinski2014multi} using TensorFlow
\citep{abadi2016tensorflow} and Keras \citep{chollet2015keras}.
Hyperparameters were tuned using Bayesian optimisation via KerasTuner
\citep{omalley2019kerastuner}, minimizing validation root mean square
error (RMSE) over 100 trials. The search space included dropout rate,
batch normalization configuration, input resolution, and the inclusion
of auxiliary features.

Further details on the synthetic data-generating process, parameter
settings, sampling scheme, example residual plots, and hyperparameter
search configuration are provided in Appendix A and Appendix C.

\section{Statistical Testing}\label{sec-model-statistical-testing}

Under the null hypothesis \(H_0\), corresponding to a correctly
specified model, the distance satisfies \(D = 0\) because \(P = Q\). In
practice, however, the estimated distance \(\hat{D}\) is generally
non-zero, even for null plots, due to sampling variability and
imperfections in the computer vision model. Consequently, statistical
significance should be assessed relative to the distribution of
estimated distances obtained from null plots rather than by the
magnitude of \(\hat{D}\) alone.

To calibrate \(\hat{D}\), we adopt the residual rotation procedure used
for null plot generation in \citet{buja2009statistical}. This involves
drawing an auxiliary response \(\boldsymbol{w}\) from
\(\mathcal{N}(\boldsymbol{0}_n, \mathbf{I}_n)\) and compute the
projected residuals
\(\hat{\boldsymbol{e}}_w = \boldsymbol{R}\boldsymbol{w}\). These are
then rescaled to match the Euclidean norm of the observed residuals,
\(\tilde{\boldsymbol{e}}_w = \hat{\boldsymbol{e}}_w \cdot \frac{\|\hat{\boldsymbol{e}}\|}{\|\hat{\boldsymbol{e}}_w\|},\)
so that \(\|\tilde{\boldsymbol{e}}_w\| = \|\hat{\boldsymbol{e}}\|\). A
null plot is then the scatter plot of
\((\hat{\boldsymbol{y}},\, \tilde{\boldsymbol{e}}_w)\), which under the
null hypothesis of a correctly specified model is statistically
indistinguishable from the true residual plot
\((\hat{\boldsymbol{y}},\, \hat{\boldsymbol{e}})\).

Let \(\hat{D}\) denote the estimated distance for the true residual plot
and let \(\{\hat{D}_{null}^{(i)}\}_{i=1}^{m}\) denote the estimated
distances for \(m\) null plots generated under \(H_0\). For a lineup
containing \(m + 1\) plots (one true plot and \(m\) null plots), the
visual inference decision rule is
\[\text{Reject } H_0 \quad \Longleftrightarrow \quad \hat{D} > \max_{1\le i\le m} \hat{D}_{null}^{(i)}.\]
This corresponds to the standard lineup protocol, where the true
residual plot must be identified as the most visually distinct plot.

More generally, the empirical distribution of
\(\{\hat{D}_{null}^{(i)}\}_{i=1}^{m}\) provides an estimate of the null
distribution of the test statistic. Let \(Q_{null}(\tau)\) denote the
empirical \(\tau\)-quantile of this distribution. A level-\(\alpha\)
test is then given by
\[\text{Reject } H_0 \quad \Longleftrightarrow \quad \hat{D} \ge Q_{null}(1-\alpha).\]
Equivalently, a Monte Carlo \(p\)-value can be computed as
\[\hat{p} = \frac{1}{m + 1} + \frac{1}{m + 1}\sum_{i=1}^{m} \mathbb{I}\left( \hat{D}_{null}^{(i)} \ge \hat{D} \right).\]
This is the standard simulation-based estimator of the tail probability
under \(H_0\). For computational efficiency, quantiles of the null
distribution may be pre-computed over a range of sample sizes and stored
in a lookup table, allowing approximate \(p\)-values to be obtained
without generating new null plots.

\section{Bootstrap Variability
Assessment}\label{sec-bootstrap-assessment}

Bootstrap methods are commonly used in linear regression to assess
parameter variability without strong distributional assumptions
\citep{davison1997bootstrap, efron1994introduction}. This involves
resampling the observed data (pairs of responses and predictors) with
replacement and refitting the model on each bootstrap sample.

Similarly, this case-resampling bootstrap can be used to assess the
variability of the estimated distance \(\hat{D}\). For each bootstrap
sample \(i=1, \ldots, n_{boot}\), a regression model \(M_{boot}^{(i)}\)
is refitted using the resampled data, producing a residual plot
\(V_{boot}^{(i)}\) and a corresponding estimated distance
\(\hat{D}_{boot}^{(i)}\). The empirical distribution of
\(\{\hat{D}_{boot}^{(i)}\}_{i=1}^{n_{boot}}\) provides an estimate of
the sampling distribution of \(\hat{D}\), from which confidence
intervals may be constructed.

More generally, each bootstrap model \(M_{boot}^{(i)}\) induces its own
null distribution of estimated distances. Let \(Q_{boot}^{(i)}(\tau)\)
denote the \(\tau\)-quantile of the corresponding null distribution. A
level-\(\alpha\) test for the \(i\)-th bootstrap model is then given by
\[\text{Reject } H_0 \quad \Longleftrightarrow \quad \hat{D}_{boot}^{(i)} \ge Q_{boot}^{(i)}(1-\alpha).\]
The proportion of bootstrap models for which \(H_0\) is rejected,
\[\frac{1}{n_{boot}}\sum_{i=1}^{n_{boot}}\mathbb{I}\left(\hat{D}_{boot}^{(i)} \ge Q_{boot}^{(i)}(1-\alpha)\right),\]
estimates how often the fitted regression model would be judged
misspecified under repeated sampling from the same data-generating
process.

This procedure is computationally expensive because it requires
evaluating \(n_{boot}(m + 1)\) residual plots, where \(m\) denotes the
number of null plots per bootstrap sample. In practice, the
bootstrap-specific critical values \(Q_{boot}^{(i)}(1-\alpha)\) may be
approximated by the corresponding quantile \(Q_{null}(1-\alpha)\) from
the original null distribution, substantially reducing the computational
burden.

\section{Results}\label{sec-model-results}

\subsection{Model Performance}\label{model-performance}

Table \ref{tab:performance} summarizes the test performance of the
optimized models across three input sizes, using 80,000 training samples
and 8,000 test samples generated as described in Section
\ref{sec-model-data-generation}. The \(32 \times 32\) model consistently
outperformed others, with a mean absolute error of approximately
\(0.43\), a negligible deviation given the typical \(D\) range of \(0\)
to \(7\). High \(R^2\) values also indicated strong linear correlation
between predictions and targets. Based on these results, we used the
best-performing \(32 \times 32\) model for subsequent analyses.

Figure \ref{fig:model-performance} shows a hexagonal heatmap of
\(D - \hat{D}\) versus \(D\). Smoothing curves \citep[fitted by
generalized additive models,][]{hastie2017generalized} reveal that all
models performed well for \(1.5 < D < 6\), where no structural issues
were observed. Over-prediction occurred when \(D < 1.5\), and
under-prediction primarily when \(\hat{D} > 6\).

For null plots (\(D = 0\)), over-prediction was expected (see Section
\ref{sec-model-statistical-testing}), but not under-prediction.
Therefore, we analysed the relationship between residuals and all the
factors involved in the data generating process. We found that most
deviations stemmed from non-linearity and the presence of a second
predictor in the synthetic data model, where small error variances
caused under-predictions and large error variances caused
over-prediction, as illustrated in Figure \ref{fig:over-under}.

To investigate further, we stratified the train and test set by
violation type and re-evaluated performance (Table
\ref{tab:data-overall}). It was found that null plots had the poorest
metrics, while non-normality cases were easiest to predict, with RMSE
around \(0.3\). Non-linearity (\(\text{RMSE} \approx  0.8\)) was harder
to assess than heteroskedasticity (\(\text{RMSE} \approx  0.6\)) or
non-normality (\(\text{RMSE} \approx  0.3\)). Plots with multiple
violations showed intermediate performance.

\begin{table}

\caption{\label{tab:performance}The test performance of three optimized models with different input sizes. The metrics are computed by comparing the estimated distance $\hat{D}$ (model output) and the target distance $D$ generated from the synthetic data model. RMSE represents the root mean squared error; $R^2$ is the squared correlation between the two quantities; MAE denotes the mean absolute error; and Huber loss refers to the average Huber loss computed over the test set.}
\centering
\begin{tabular}[t]{lrrrr}
\toprule
 & RMSE & $R^2$ & MAE & Huber loss\\
\midrule
$32 \times 32$ & 0.660 & 0.901 & 0.434 & 0.18\\
$64 \times 64$ & 0.674 & 0.897 & 0.438 & 0.19\\
$128 \times 128$ & 0.692 & 0.892 & 0.460 & 0.20\\
\bottomrule
\end{tabular}
\end{table}

\begin{figure}[!h]

{\centering \includegraphics[width=1\linewidth]{paper_files/figure-latex/model-performance-1} 

}

\caption{Hexagonal heatmap for difference in $D$ and $\hat{D}$ vs $D$ on test data for three optimized models with different input sizes. The brown lines are smoothing curves produced by fitting generalized additive models. Over-prediction and under-prediction can be observed for small $D$ and large $D$ respectively.}\label{fig:model-performance}
\end{figure}

\begin{figure}[!h]

{\centering \includegraphics[width=1\linewidth]{paper_files/figure-latex/over-under-1} 

}

\caption{Scatter plots for difference in $D$ and $\hat{D}$ vs $\sigma$ on test data for the $32 \times 32$ optimized model. The data is grouped by whether the regression has only non-linearity violation, and whether it includes a second predictor in the regression formula. The brown lines are smoothing curves produced by fitting generalized additive models. Under-prediction mainly occurs when the data-generating process has small $\sigma$, a second predictor, and only non-linearity as the model violation.}\label{fig:over-under}
\end{figure}

\subsection{Comparison with Human Visual Inference and Conventional
Tests}\label{comparison-with-human-visual-inference-and-conventional-tests}

\subsubsection{Overview of the Human Subject
Experiment}\label{overview-of-the-human-subject-experiment}

In order to check the validity of the proposed computer vision model,
residual plots presented in the human subject experiment conducted by
\citet{li2024plot} was assessed. The study collected 7,974 responses
across 1,152 lineups, each containing one randomly positioned true
residual plot and 19 null plots. Of these, 24 were attention-check
lineups with highly obvious patterns, 36 were null lineups containing
only null plots, 279 involved uniformly distributed predictors and were
evaluated by 11 participants each, and the remaining 813 involved
discrete, skewed, or normally distributed predictors and were evaluated
by 5 participants each. Attention-check and null lineups are excluded
from the present analysis.

Participants were recruited through Prolific. Most were not experts in
residual plots, and 56.7\% reported no prior experience with studies
involving data visualisations. The sample was approximately
gender-balanced, more than half held a diploma or bachelor's degree, and
almost all participants were between 18 and 39 years of age.
Consequently, the results primarily reflect the ability of non-experts
to distinguish true residual plots from null plots based on visual
differences rather than specialised statistical training.

The residual plots in \citet{li2024plot} were generated from a special
case of the synthetic data model used in this study. Model violations
were introduced independently, so non-linearity and heteroskedasticity
did not co-occur within the same lineup. In addition, the experimental
design did not consider non-normality or multiple predictors.

\subsubsection{Model Performance on the Human-evaluated
Data}\label{model-performance-on-the-human-evaluated-data}

Each lineup in \citet{li2024plot} contains one true residual plot and 19
null plots. While the true residual plot's distance \(D\) depends on the
data-generating process, null plots have \(D = 0\). We used our
optimized computer vision model to estimate \(D\) for all plots. To
ensure fair comparison, we reject \(H_0\) if the true residual plot has
the highest estimated distance. Conventional tests, including the Ramsey
RESET \citep{ramsey1969tests} for non-linearity and the Breusch-Pagan
test \citep{breusch1979simple} for heteroskedasticity, were also applied
to the same data.

Table \ref{tab:experiment-performance} reports performance metrics for
\(\hat{D}\) on true residual plots. While the performance is slightly
worse than on the test data provided in Table \ref{tab:performance}, the
mean absolute error remains low and the correlation between predictions
and true values remains high. Consistent with results in Table
\ref{tab:data-overall}, non-linearity cases are harder to predict than
heteroskedasticity cases.

\begin{table}

\caption{\label{tab:experiment-performance}The performance of the $32 \times 32$ model on the data used in the human subject experiment.}
\centering
\begin{tabular}[t]{lrrrr}
\toprule
Violation & RMSE & $R^2$ & MAE & Huber loss\\
\midrule
heteroskedasticity & 0.721 & 0.852 & 0.553 & 0.235\\
non-linearity & 0.738 & 0.770 & 0.566 & 0.246\\
\bottomrule
\end{tabular}
\end{table}

\begin{table}

\caption{\label{tab:human-conv-table}Summary of the comparison of decisions made by computer vision model with decisions made by conventional tests and visual tests conducted by human.}
\centering
\begin{tabular}[t]{lrrr}
\toprule
Violations & \#Samples & \#Agreements & Agreement rate\\
\midrule
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Compared with conventional tests}}\\
\hspace{1em}heteroskedasticity & 540 & 464 & 0.8593\\
\hspace{1em}non-linearity & 576 & 459 & 0.7969\\
\addlinespace[0.3em]
\multicolumn{4}{l}{\textbf{Compared with visual tests conducted by human}}\\
\hspace{1em}heteroskedasticity & 540 & 367 & 0.6796\\
\hspace{1em}non-linearity & 576 & 385 & 0.6684\\
\bottomrule
\end{tabular}
\end{table}

Table \ref{tab:human-conv-table} compares the model's rejection
decisions with those of conventional tests and human visual tests.
Agreement rates are 85.95\% for heteroskedasticity cases and 79.69\% for
non-linearity cases, higher than those observed for human visual tests
(67.96\% and 66.84\%, respectively). This suggests that the model aligns
more closely with the best available conventional tests. However, as
Figure \ref{fig:conv-mosaic} shows, the model does not always reject
when conventional tests do, indicating a lower sensitivity to model
violations.

\begin{figure}[!h]

{\centering \includegraphics[width=1\linewidth]{paper_files/figure-latex/conv-mosaic-1} 

}

\caption{Rejection rate ($p$-value $\leq0.05$) of computer vision models conditional on conventional tests on non-linearity (left) and heteroskedasticity (right) lineups displayed using a mosaic plot. When the conventional test fails to reject, the computer vision mostly fails to reject the same plot as well as indicated by the height of the top right yellow rectangle, but there are non negligible amount of plots where the conventional test rejects but the computer vision model fails to reject as indicated by the height of the top left yellow rectangle.}\label{fig:conv-mosaic}
\end{figure}

To further illustrate these patterns, Figure \ref{fig:pcp} presents
parallel coordinate plots comparing decisions from human visual tests,
the computer vision model, and conventional tests. All three agree in
about 50\% of cases. When humans do not reject, conventional tests
reject in about half of those cases, whereas the model rejects in only
25\%. Notably, the model rarely rejects when both humans and
conventional tests do not, suggesting that while it is more sensitive
than humans, its rejection behavior is more aligned with human judgment
than with conventional tests.

\begin{figure}[!h]

{\centering \includegraphics[width=1\linewidth]{paper_files/figure-latex/pcp-1} 

}

\caption{Parallel coordinate plots of decisions made by computer vision model, conventional tests and visual tests made by human. All three agree in around 50\% of cases. The model rejects less often than conventional tests when humans do not, and rarely rejects when both others do not, indicating closer alignment with human judgment.}\label{fig:pcp}
\end{figure}

Figure \ref{fig:power} plots rejection decisions against the true
distance \(D\). Compared to conventional tests, the computer vision
model rejects fewer cases when \(D < 4\), but a similar number of cases
when \(D > 4\). This indicates that the model is less sensitive to minor
deviations from model assumptions, while remaining comparably sensitive
to more substantial violations. Visual tests are the least sensitive
overall, showing few rejections for \(D < 2\), and requiring a higher
threshold (\(D > 5\)) for near-universal rejection, compared to
\(D > 4\) for both the model and conventional tests.

\begin{figure}[!h]

{\centering \includegraphics[width=1\linewidth]{paper_files/figure-latex/power-1} 

}

\caption{Comparison of power of visual tests, conventional tests and the computer vision model. Marks along the x-axis at the bottom of the plot represent rejections made by each type of test. Marks at the top of the plot represent acceptances. Power curves are fitted by logistic regression models with no intercept but an offset equals to $\text{log}(0.05/0.95)$. The model is less sensitive than conventional tests for small $D$ but similarly sensitive for large $D$. Visual tests are least sensitive overall. The model’s curve lies between those of conventional and visual tests.}\label{fig:power}
\end{figure}

Finally, the power curves in Figure \ref{fig:power} are fitted using
logistic regression without intercepts and with an offset of
\(\log(0.05/0.95)\) to ensure a 5\% rejection rate under \(H_0\). The
model's rejection curve consistently lies between those of conventional
and human visual tests, indicating potential to further align its
decision boundary with human visual assessment.

\subsubsection{\texorpdfstring{Adjusted
\(\delta\)-difference}{Adjusted \textbackslash delta-difference}}\label{adjusted-delta-difference}

In the experiment conducted by \citet{li2024plot}, participants could
select multiple plots per lineup. To reflect detection confidence, a
weighted detection rate was computed for each lineup: selecting zero
plots yielded a weight of 0.05; otherwise, if the true residual plot was
selected, its weight was the inverse of the number of selections.

To evaluate the proposed distance measure, we could examine the
relationship between the weighted detection rate and the
\(\delta\)-difference statistic from \citet{chowdhury2018measuring}:

\[
\delta = \bar{d}_{\text{true}} - \underset{j}{\text{max}}\left(\bar{d}_{\text{null}}^{(j)}\right) \quad \text{for}~j = 1,...,m-1,
\]

\noindent where \(\bar{d}_{\text{true}}\) is the mean distance between
the true residual plot and all null plots, and
\(\bar{d}_{\text{null}}^{(j)}\) is the mean distance from null plot
\(j\) to other nulls. These averages help address asymmetries in
pairwise distances.

However, our method only compares each plot to a theoretically ``good''
residual plot, making the original formulation inapplicable. Moreover,
since \(D_{\text{null}} = 0\) by definition and \(D\) can not be derived
from an image, we instead focus on \(\hat{D}\), the model-estimated
distance. This leads to the adjusted \(\delta\)-difference:

\[
\delta_{\text{adj}} = \hat{D} - \underset{j}{\text{max}}\left(\hat{D}_{\text{null}}^{(j)}\right) \quad \text{for}~j = 1,...,m-1,
\]

\noindent where \(\hat{D}_{\text{null}}^{(j)}\) is the estimated
distance for the \(j\)-th null plot, and \(m\) is the number of plots in
a lineup.

\begin{figure}[!h]

{\centering \includegraphics[width=0.8\linewidth]{paper_files/figure-latex/delta-1} 

}

\caption{A weighted detection rate vs adjusted $\delta$-difference plot. The brown line is smoothing curve produced by fitting generalized additive models. Detection generally increases with positive $\delta_{\text{adj}}$, but variability and exceptions highlight the distance measure's imperfect alignment with human perception.}\label{fig:delta}
\end{figure}

Figure \ref{fig:delta} displays the scatter plot of the weighted
detection rate against \(\delta_{\text{adj}}\). It shows that weighted
detection generally increases with \(\delta_{\text{adj}}\), especially
when it is positive. This suggests that the differences in \(\hat{D}\)
capture some aspect of the visual separability between the true and null
plots as perceived by humans, with larger positive differences generally
indicating greater distinctiveness. However, the considerable
variability in detection rates for similar \(\delta_{\text{adj}}\)
values implies that \(\hat{D}\) does not fully account for all factors
influencing human perception, and the alignment remains imperfect. A
negative \(\delta_{\text{adj}}\) suggests some null plots may appear
more visually distinctive to humans than the true residual plot. In some
instances, the weighted detection rate is close to one despite a
negative \(\delta_{\text{adj}}\). This discrepancy implies that the
distance measure may not perfectly reflect actual human behavior.

\section{Examples}\label{sec-examples}

In this section, we present the performance of the trained computer
vision model on three example datasets, including the dataset associated
with the residual plot displaying a ``left-triangle'' shape, the Boston
housing dataset \citep{harrison1978hedonic}, and the ``dino'' datasets
from the from the \texttt{datasauRus} package \citep{datasaurus}.

In the first case, both the model and human inspection correctly avoid
rejecting \(H_0\) when it is true, contrary to conventional tests,
highlighting the necessity of visual examination. The second case shows
a clear model violation detected by all tests, demonstrating the model's
practical use for less intricate tasks. The third case involves an
unusual deviation where the model and humans reject \(H_0\), but some
conventional tests do not, illustrating the benefits of visual-based
decision-making.

\subsection{Left-triangle}\label{left-triangle}

In Section \ref{sec-model-introduction}, we introduced a residual plot
(Figure \ref{fig:false-check}A) where the ``left-triangle'' shape could
be misinterpreted as evidence of heteroskedasticity. Although the
residuals are drawn from a correctly specified model, the Breusch-Pagan
test rejects \(H_0\) (\(p = 0.046\)). This visual artifact stems from
the skewed distribution of fitted values, as later illustrated in the
lineup in Figure \ref{fig:lineup}A, where similar ``left-triangle''
patterns appear across all residual plots. Since the true plot (at
position 10) is visually indistinguishable from the null plots, a visual
test would not reject \(H_0\).

The computer vision model yields the same conclusion from the lineup. As
shown in Figure \ref{fig:false-check}C, the estimated distance
\(\hat{D}\) falls well below the 95\% quantile of the null distribution,
with a \(p\)-value of \(0.33\). The bootstrapped distribution further
suggests that rejection of the fitted model is highly unlikely.
Together, the visual and model-based tests do not reject \(H_0\), in
contrast to the Breusch-Pagan test, which lacks the context provided by
null plots and may be misled by visual artifacts.

To further interpret the model's output, the attention map in Figure
\ref{fig:false-check}B, computed as the gradient of the output with
respect to the grayscale input, shows that the top-right and
bottom-right corners of the residual plot have the most influence,
corresponding to the triangle's vertices. In addition, a principal
component analysis (PCA) of the 256 features extracted by the model's
global pooling layer (Figure \ref{fig:false-check}D) shows that null and
bootstrapped plots cluster together in the space defined by the first
two principal components, and the true residual plot is covered by the
cluster. This overlap reinforces the conclusion that the true plot is
visually indistinct, aligning with our interpretation of the lineup.

\begin{figure}[!h]

{\centering \includegraphics[width=0.8\linewidth]{paper_files/figure-latex/false-check-1} 

}

\caption{A summary of the residual plot assessment evaluated on 200 null plots and 200 bootstrapped plots. (A) The true residual plot exhibiting a ``left-triangle" shape. (B) The attention map highlights the top-right and bottom-right corners of the residual plot as the most influential.  (C) The density plot shows estimated distances for null (yellow) and bootstrapped (green) plots. The fitted model is not rejected because $\hat{D} < Q_{null}(0.95)$. (D) Null and bootstrapped plots cluster together in the space defined by the first two principal components of the global pooling layer. The cluster also covers the true residual plot.}\label{fig:false-check}
\end{figure}

\subsection{Boston Housing}\label{boston-housing}

The Boston housing dataset, originally published by
\citet{harrison1978hedonic}, provides insights into housing in the
Boston, Massachusetts area. For illustration, we use a reduced Kaggle
version containing 489 observations and four variables: average number
of rooms per dwelling (RM), percentage of lower status population
(LSTAT), pupil-teacher ratio by town (PTRATIO), and median home value
(MEDV). We fit a linear regression model with MEDV as the response and
the remaining variables as predictors, focusing on detecting
non-linearity, because the relationships between RM and MEDV or LSTAT
and MEDV are non-linear.

Figure \ref{fig:boston-check} summarizes the model evaluation. The
residual plot (Figure \ref{fig:boston-check}A) reveals a distinct
``U''-shaped pattern, suggesting non-linearity. The RESET test strongly
rejects \(H_0\) with a very small \(p\)-value, and the computer vision
model yields a large estimated distance \(\hat{D}\), well above the 95\%
quantile of the null distribution (\(p\text{-value} = 0.00498\)). The
bootstrapped distribution also shows widespread rejection, indicating
the model is likely misspecified. The attention map (Figure
\ref{fig:boston-check}B) highlights the central region of the residual
plot, corresponding to the turning point of the ``U'', as most
influential. In the PCA projection (Figure \ref{fig:boston-check}D),
bootstrapped and null plots form two distinct clusters, emphasizing the
visual separability. This aligns with the lineup in Figure
\ref{fig:lineup}B, where the true plot stands out clearly. A human
visual test would also likely reject \(H_0\) in this case.

\begin{figure}[!h]

{\centering \includegraphics[width=0.8\linewidth]{paper_files/figure-latex/boston-check-1} 

}

\caption{A summary of the residual plot assessment for the Boston housing fitted model evaluated on 200 null plots and 200 bootstrapped plots. (A) The true residual plot exhibiting a ``U" shape. (B) The attention map highlights the central region of the ``U" shape as the most influential part of the residual plot. (C) The density plot shows estimated distances for null (yellow) and bootstrapped (green) plots. The fitted model is rejected because $\hat{D} \geq Q_{null}(0.95)$. (D) Bootstrapped and null plots form distinct clusters in the space of the first two principal components from the global pooling layer, highlighting their visual separability.}\label{fig:boston-check}
\end{figure}

\subsection{DatasauRus}\label{datasaurus}

Beyond detecting common issues like non-linearity, heteroskedasticity,
and non-normality, the computer vision model can also identify unusual
visual artifacts, such as shapes resembling real-world objects, as long
as such patterns do not appear in null plots. These cases are
challenging to categorize using conventional model diagnostics, so we
compare the model's output with results from the RESET test,
Breusch-Pagan test, and Shapiro-Wilk test \citep{shapiro1965analysis}.

The ``dino'' dataset from the \texttt{datasauRus} R package illustrates
this situation. It contains only two variables, \(x\) and \(y\), but
fitting a regression model produces a residual plot that clearly
resembles a dinosaur (Figure \ref{fig:dino-check}A). This pattern is
visually distinctive in the lineup shown in Figure \ref{fig:lineup}C,
where a human visual test would undoubtedly reject \(H_0\).

Consistent with this, the computer vision model assigns a distance
\(\hat{D}\) above the 95\% quantile of the null distribution
(\(p\text{-value} = 0.00498\)), leading to rejection of \(H_0\). The
bootstrapped distribution further supports this, with most fitted models
also being rejected. In contrast, the RESET and Breusch-Pagan tests
yield \(p\)-values above \(0.3\), suggesting no violation. Only the
Shapiro-Wilk test rejects normality with a small \(p\)-value.

Crucially, the attention map in Figure \ref{fig:dino-check}B highlights
the dinosaur shape, indicating that the model's decision is driven by
human-perceptible features. The model appears to capture contours and
outlines in a manner similar to human visual interpretation. In the PCA
plot (Figure \ref{fig:dino-check}D), the cluster of bootstrapped plots
is positioned at the corner of the cluster of null plots, isolated from
the cluster of null plots.

In practice, such visual artifacts would be difficult to detect without
inspecting the residual plot directly. Furthermore, analysts do not
always test for normality, and even when violations are found, they are
often deemed acceptable due to the robustness of linear regression under
quasi-likelihood theory. This example highlights the value of visual
diagnostics and the unique role of the proposed computer vision model in
supporting them.

\begin{figure}[!h]

{\centering \includegraphics[width=0.8\linewidth]{paper_files/figure-latex/dino-check-1} 

}

\caption{A summary of the residual plot assessment for the datasauRus fitted model evaluated on 200 null plots and 200 bootstrapped plots. (A) The residual plot exhibits a ``dinosaur" shape. (B) The attention map highlights the ``dinosaur" shape, indicating the model's decision is driven by human-recognizable features.(C) The density plot shows estimated distances for null (yellow) and bootstrapped (green) plots. The fitted model is rejected because $\hat{D} \geq Q_{null}(0.95)$. (D) The bootstrapped plots cluster at the corner of the null plot cluster, yet remain isolated in the space defined by the first two principal components of the global pooling layer.}\label{fig:dino-check}
\end{figure}

\begin{figure}[!h]

{\centering \includegraphics[width=1\linewidth]{paper_files/figure-latex/lineup-1} 

}

\caption{Lineups of residual plots for the ``left-triangle", ``Boston housing", and ``datasauRus" datasets. (A) True plot at position 10; no clear visual difference. (B) True plot at position 7; ``U"-shape clearly stands out. (C) True plot at position 17; distinctly artificial and easily identifiable.}\label{fig:lineup}
\end{figure}

\section{Limitations and Future Work}\label{limitations-and-future-work}

While the computer vision model performs well under the synthetic data
generation scheme and across the three illustrative examples, this study
has several limitations that point to directions for future work.

First, the proposed distance measure assumes the true model follows a
classical normal linear regression framework, which may be restrictive.
Although we do not explore relaxation of this assumption here, future
work could extend the approach to other types of regression models. One
possibility is to define a distance measure tailored to each model class
and re-train the computer vision model accordingly. To reduce
computational cost, the convolutional blocks from our current model
could be reused via transfer learning, as it is already effective at
capturing visual features. Alternatively, transforming residuals to
approximate normality and constant variance could allow for meaningful
comparisons under our current distance measure. However, if raw
residuals are used, the interpretation remains valid only when the
visual differences between the true and null plots are detectable by the
proposed distance measure.

Second, this study focused solely on the standard residuals vs.~fitted
values plot, leaving out other common diagnostic plots such as residuals
vs.~predictors and Q-Q plots. These alternative plots may offer
additional information and could be incorporated into a broader visual
testing framework in future research.

Finally, we chose a relatively simple computer vision architecture to
establish a baseline for automated visual inference. While the current
model shows promise, there is room to improve its alignment with human
judgment. Achieving this may require external data from surveys or
controlled experiments to better understand how human observers
interpret residual plots and how these judgments differ from the model's
outputs.

\section{Conclusions}\label{conclusions}

In this paper, we have introduced a distance measure based on the
Kullback-Leibler divergence to quantify disparity between the residual
distribution of a fitted classical normal linear regression model and
the reference distribution under correct specification. This measure
captures the extent of model violations and forms the basis of a
computer vision model that estimates the distance using residual plots
as input.

The estimated distance supports a formal statistical testing procedure
by comparing the true residual plot against null plots generated from
the fitted model. Through bootstrapping and model refitting, we also
evaluate how often a correctly specified model would be flagged as
misspecified under repeated sampling.

The trained computer vision model performs well on both training and
test data, though its performance is somewhat lower for non-linear
patterns. Statistical tests based on the model's predicted distance show
lower sensitivity than conventional tests but higher sensitivity than
human visual tests. Importantly, the predicted distance broadly aligns
with the strength of visual signals perceived by humans, though further
improvements are possible.

We demonstrate the method across several scenarios, highlighting its
effectiveness and its conceptual alignment with visual inference. Both
visual and distance-based tests act as omnibus procedures, detecting a
wide range of model violations collectively. In contrast, conventional
tests such as RESET and Breusch-Pagan target specific assumptions,
making them less flexible and potentially harder to combine without
adjusting for multiple testing.

Overall, our approach offers a practical tool to support regression
diagnostics by reducing the manual effort required for residual plot
inspection. While we recommend analysts to continue reading residual
plots whenever feasible, our method can augment the process, either as
an automated screening tool or a supplement to human judgment.

\section*{Supplementary Materials}\label{supplementary-materials}
\addcontentsline{toc}{section}{Supplementary Materials}

\begin{description}
\item{Appendix:} The appendix includes more details about the synthetic data generation process, neural network layers used in the work, model training, and model violation index. (appendix.pdf, Portable Document Format file)
\end{description}

\section*{Acknowledgement}\label{acknowledgement}
\addcontentsline{toc}{section}{Acknowledgement}

These \texttt{R} packages were used for the work: \texttt{tidyverse}
\citep{tidyverse}, \texttt{lmtest} \citep{lmtest}, \texttt{mpoly}
\citep{mpoly}, \texttt{ggmosaic} \citep{ggmosaic}, \texttt{kableExtra}
\citep{kableextra}, \texttt{patchwork} \citep{patchwork}, \texttt{glue}
\citep{glue}, \texttt{ggpcp} \citep{ggpcp}, \texttt{here} \citep{here},
and \texttt{reticulate} \citep{reticulate}.

The article was created with R packages \texttt{rticles}
\citep{rticles}, \texttt{knitr} \citep{knitr} and \texttt{rmarkdown}
\citep{rmarkdown}. The project's GitHub repository
(\url{https://github.com/TengMCing/auto_residual_reading_paper})
contains all materials required to reproduce this article.

We acknowledge the use of ChatGPT (OpenAI, GPT-4, accessed July 2026) to
improve the clarity and fluency of the manuscript text. All content was
reviewed and verified by the authors to ensure accuracy and integrity.

\section*{Data Availability
Statement}\label{data-availability-statement}
\addcontentsline{toc}{section}{Data Availability Statement}

The data that support the findings of this study are openly available in
the project's GitHub repository
(\url{https://github.com/TengMCing/auto_residual_reading_paper}).

The human subject data used in this study were originally collected
under ethical approval obtained by the original authors
\citet{li2024plot}, who have made the data publicly available for re-use
under an MIT license. As this study involves secondary analysis of
de-identified, publicly available data, separate ethical approval is not
required for the present analysis, in accordance with the journal's
policy on secondary use of anonymized data.

\section*{Disclosure Statement}\label{disclosure-statement}
\addcontentsline{toc}{section}{Disclosure Statement}

No potential conflict of interest was reported by the author(s).

\bibliographystyle{tfcad}
\bibliography{bibliography.bib}





\end{document}
