---
format: quarto-anu-letter-pdf
author:
  - name: "\u200B" # I need to sign this
    position: Postdoctoral Research Fellow 
    affiliation:
      - name: Australian National University
        department: Research School of Finance, Actuarial Studies and Statistics
        address: "26C Kingsley Street"  
        city: Canberra
        country: Australia
        postal-code: 2600
address:
  - Editors
  - Journal of Computational and Graphical Statistics
subject: "Submission of Manuscript: Automated Assessment of Residual Plots with Computer Vision Models"
# subject-title: "Editors"
title: Letter from ANU
opening: "Dear Prof. Chen and Prof. Sangalli,"
closing: "Sincerely,"
keep-tex: true
---

Please consider our manuscript "Automated Assessment of Residual Plots with Computer Vision Models" for publication in the Journal of Computational and Graphical Statistics.

This paper builds on our previous work, "A Plot is Worth a Thousand Tests: Assessing Residual Diagnostics with the Lineup Protocol" (JCGS), which provided empirical evidence for the effectiveness of visual evaluation of residual plots through crowd-sourced lineup experiments. While that study highlighted the cost and effort of human evaluations, this work advances automation through computer vision. We introduce a model trained to predict a custom distance measure that quantifies the discrepancy between residuals and theoretically "good" distributions. Building on these predictions, we construct a statistical testing framework aligned with the original lineup protocol, ensuring a valid visual test. When evaluated on the earlier experiment data, the model performs slightly worse than humans but surpasses conventional statistical tests due to its reduced sensitivity to minor deviations from model assumptions. We further demonstrate that the model, like human observers, relies on visual patterns and shapes, making it a practical tool for reducing manual effort in residual plot diagnostics. This approach should be of particular interest to readers concerned with model diagnostics and the automation of visual data analysis.

Thank you for the consideration of this manuscript. We believe that it is a good fit for the Journal of Computational and Graphical Statistics.
